version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: amdariuserpassword
      POSTGRES_USER: amdariuser
      POSTGRES_DB: amdaridb
    volumes:
      - postgresdb-volume:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  postgresdb-volume: {}
